trade_org = {
    "Tradebooks : TR Fiction & Lit (TRF)": [
        "TRF : Alum",
        "TRF : Award Winner",
        "TRF : Board Books",
        "TRF : Chapter Books",
        "TRF : Childrens/Juvenile",
        "TRF : Classics",
        "TRF : Comics & Graphic Novels",
        "TRF : Drama",
        "TRF : Faculty",
        "TRF : Fiction",
        "TRF : Fiction Anthology",
        "TRF : Horror",
        "TRF : Kids Picture Books",
        "TRF : Manga",
        "TRF : Middle Reader Graphic Novels",
        "TRF : Middler Reader",
        "TRF : Mystery",
        "TRF : New Fiction Hardcover",
        "TRF : New Fiction Paperback",
        "TRF : Poetry",
        "TRF : Romance",
        "TRF : Sci Fi & Fantasy",
        "TRF : Young Adult",
    ],
    "Tradebooks : TR Nonfiction (TRN)": [
        "TRN : Acacemic New",
        "TRN : Africana",
        "TRN : Alum",
        "TRN : Ancient History",
        "TRN : Anthropology",
        "TRN : Architecture",
        "TRN : Art",
        "TRN : Art/Artists",
        "TRN : Art/History&Criticism",
        "TRN : Art/Instruction",
        "TRN : Award Winners",
        "TRN : Biography",
        "TRN : Business",
        "TRN : Child Care",
        "TRN : Childrens/Juvenile",
        "TRN : Computer Books",
        "TRN : Cooking",
        "TRN : Crafts & Hobbies",
        "TRN : Current Events",
        "TRN : Dance",
        "TRN : Design",
        "TRN : Diversity",
        "TRN : Education",
        "TRN : Engineering",
        "TRN : Essays",
        "TRN : European History",
        "TRN : Faculty",
        "TRN : Fashion",
        "TRN : Food Literature",
        "TRN : Gardening",
        "TRN : Gender Studies",
        "TRN : General History",
        "TRN : Graphic Novels",
        "TRN : Health",
        "TRN : History/Asia",
        "TRN : History/Latin America",
        "TRN : History/Middle East",
        "TRN : Homes",
        "TRN : Humor",
        "TRN : Kids Biography",
        "TRN : Kids Diversity",
        "TRN : Kids General Nonfiction",
        "TRN : Kids History",
        "TRN : Kids Mythology",
        "TRN : Kids Science",
        "TRN : LGBTQ+",
        "TRN : Literary Criticism",
        "TRN : Math",
        "TRN : Media Studies",
        "TRN : Medicine",
        "TRN : Music",
        "TRN : Mythology",
        "TRN : Nature",
        "TRN : New England",
        "TRN : New Nonfiction Hardcover",
        "TRN : New Nonfiction Paperback",
        "TRN : Pagan/New Age",
        "TRN : Performing Arts",
        "TRN : Pets",
        "TRN : Philosophy",
        "TRN : Photography",
        "TRN : Political Science",
        "TRN : Psychology",
        "TRN : Religion",
        "TRN : Religion/Christianity",
        "TRN : Relgion/Eastern",
        "TRN : Religion/Holy Texts",
        "TRN : Relgion/Islam",
        "TRN : Religion/Judaism",
        "TRN : Science",
        "TRN : Self Help",
        "TRN : Sociology",
        "TRN : Sports",
        "TRN : Travel Literature",
        "TRN : Travel/Domestic",
        "TRN : Travel/Foreign",
        "TRN : True Crime",
        "TRN : TV & Film",
        "TRN : Us History",
        "TRN : World History",
        "TRN : Young Adult Nonfiction",
    ],
    "Tradebooks : TR Reference (TRR)": [
        "TRR : Charts",
        "TRR : Dictionary",
        "TRR : Dover Math",
        "TRR : Dover Science",
        "TRR : Journals",
        "TRR : Language Instruction",
        "TRR : Law",
        "TRR : Medical",
        "TRR : Reference General",
        "TRR : Student Reference",
        "TRR : Study Guides",
        "TRR : Technology Reference",
        "TRR : Test Prep",
        "TRR : Travel/Maps",
        "TRR : Writing Reference",
    ],
    "Tradebooks : TR Gifts (TRZ)": [
        "TRZ : Bargain/Remainders",
        "TRZ : Display",
        "TRZ : Games",
        "TRZ : Giantmicrobes",
        "TRZ : Giftbooks",
        "TRZ : Sidelines",
        "TRZ : Special Order",
    ],
}

cols_to_delete = [
    "Purchase Order",
    "Item #",
    "Author 2",
    "Units",
    "Discount",
    "Discount Code",
    "Format",
    "Secondary Store Category",
    "BISAC Category Code",
    "Publisher Code",
    "SAN",
    "Markup Tags",
    "UPC",
    "Number of Pages",
    "Dimensions",
    "Links",
]

cols_dtypes = {
    "ISBN 10": str,
    "EAN": str,
    "Title": str,
    "Subtitle": str,
    "List Price": float,
    "Cost": float,
    "Edition": str,
    "Print Run": str,
}

vendor_dict = {
    "Penguin Random House": "24590",
    "Simon & Schuster": "24597",
    "MPS": "24611",
    "HC": "24636",
    "IN": "24594",
    "TW": "24601",
    "NO": "24620",
    "394": "24590",
    "WI": "24637",
    "JHU": "24752",
    "ABRA": "24601",
    "CM": "24594",
    "LCQ": "24636",
    "HARB": "24620",
    "DMMQ": "24583",
    "CUNW": "24594",
    "BKVR": "24648",
    "REDB": "24759",
    "UOCP": "24594",
    "ELH": "24573",
    "HCCA": "24636",
    "NY": "24594",
    "CONS": "24594",
    "CA": "109208",
    "MIO": "24583",
    "YALE": "24620",
}

smart_quotes_map = {"“": '"', "”": '"', "‘": "'", "’": "'"}
